# Generated by Django 5.0.6 on 2024-07-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMymoney', '0002_brand_brand_en_brand_brand_tr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Tarzlar'},
        ),
        migrations.AlterModelOptions(
            name='caseshape',
            options={'verbose_name_plural': 'Şekil'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Renk'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name_plural': 'Cinsiyet'},
        ),
        migrations.AlterModelOptions(
            name='glassfeature',
            options={'verbose_name_plural': 'özellikleri'},
        ),
        migrations.AlterModelOptions(
            name='mechanism',
            options={'verbose_name_plural': 'Mekanizma'},
        ),
        migrations.AlterModelOptions(
            name='straptype',
            options={'verbose_name_plural': 'Tip'},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name_plural': 'Sitil'},
        ),
    ]
